name = "ye_gd_lower_bound"
version = "0.1.0"
defaultTargets = ["YeGDLowerBound"]

[[require]]
name = "maChenGDLowerBound"
git = "https://github.com/jianhaoma/gd-lower-bound-lean.git"
rev = "e41ce4b7e0a92b2e460f2dbc898d91e862379419"

[[lean_lib]]
name = "YeGDLowerBound"
